Correct qemu actions with tarball and postconf

diff --git a/GenBerry b/GenBerry
--- a/GenBerry
+++ b/GenBerry
@@ -74,7 +74,7 @@ function printResult #{{{
 {
     if [[ -z "$2" ]]; then local MESSAGE=""; else local MESSAGE="$2"; fi
     if [[ "$1" -ne 0 ]]; then
-        echo -e "\e[1;31m[FAIL]\e[0m\n\t$MESSAGE\n\tCheck the logs: $LOG"
+        echo -e "\e[1;31m[FAIL]\e[0m\n\t$MESSAGE\n"
         [[ -z "$3" ]] && clean
         exit 1
     else
@@ -95,12 +95,14 @@ function announce #{{{
         echo -e "* Default root password: \e[1;33m$ROOT_PW\e[0m"
     fi
     echo -e "* Kernel version: \e[1;33m$KRN_VERSION\e[0m"
+    $USE_QEMU && 
+        echo "* qemu will be used for building stuff locally."
     $USE_IMG && 
         echo -e "* Location of the image: \e[1;33m$WORK_DIR/$FILE_PREFIX$RPI_VERSION-$MODE.img\e[0m"
     $USE_TARB && 
         echo -e "* Location of the tarball: \e[1;33m$WORK_DIR/$FILE_PREFIX$RPI_VERSION-$MODE.tar.xz\e[0m"
     [[ -n $MY_CFG ]] && echo "* Kernel configuration file used: \e[1;33m$MY_CFG\e[0m"
-    $USE_MY_FSTAB && echo "* fstab file used: \e[1;33m$FSTAB_FILE\e[0m"
+    $USE_MY_FSTAB && echo -e "* fstab file used: \e[1;33m$FSTAB_FILE\e[0m"
     $MY_CFG_TXT && echo "* We use your own config.txt"
     echo -e "* RaspberryPi version: \e[1;33m$RPI_VERSION\e[0m"
     echo -e "* Architecture: \e[1;33m$MYARCH\e[0m"
@@ -109,6 +111,7 @@ function announce #{{{
     echo -e "* Timezone: \e[1;33m$TZ\e[0m"
     echo -e "* Keymaps: \e[1;33m$KEYMAPS\e[0m"
     $ADD_PORTAGE && echo "* Last portage tree will be added"
+    [[ -n $WPA_SUPP_FILE ]] && echo -e "* wpa_supplicant.conf used: \e[1;33m$WPA_SUPP_FILE\e[0m"
     $USE_TETHER && 
         {
             echo "* USB tethering will be configured"
@@ -159,6 +162,10 @@ function test_requirements #{{{
         echo -en "\t- Media not mounted: "
         [[ $(mount | grep -c "${CARD}") -eq 0 ]]
         printResult $? "${CARD} already mounted."
+    elif [[ "$USE_TARB" = true ]]; then
+        echo -en "\t- fstab file availability: "
+        [[ -n "$FSTAB_FILE" ]]
+        printResult $? "You have to provide an fstab file."
     fi
     echo -en "\t- Cross compilation tools: "
     which "${AARCH}-gcc" >> "$LOG" 2>&1
@@ -260,16 +267,21 @@ function chroot_qemu #{{{
     DEVPTS_OPTS="rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000"
     mount -o $DEVPTS_OPTS devpts "$WORK_DIR/$ROOT/dev/pts" -t devpts >> "$LOG" 2>&1
     printResult $? "Unable to mount /dev/pts."
-    echo -ne "\t- tweak to bypass bug qemu:"
+    echo -ne "\t- tweak to bypass bug qemu: "
     echo "FEATURES=\"-pid-sandbox\"" >> "$WORK_DIR/$ROOT/etc/portage/make.conf" 2>> "$LOG"
     printResult $? "Unable to insert FEATURES in make.conf."
-    echo -ne "\t- chroot"
+    echo -ne "\t- execute tasks in the chroot: "
     #cat 2>> "$LOG" << EOF | chroot "$WORK_DIR/$ROOT"
     chroot "$WORK_DIR/$ROOT" >> "$LOG" 2>&1 << EOF
     $(cat "./Configs/postinst.conf")
 EOF
+    printResult $? "Some tasks failed in the chroot.\nCheck the logs."
+    echo -ne "\t- unmount tools: "
+    for dir in "dev/pts" "dev" "proc" "sys"; do
+        umount "$WORK_DIR/$ROOT/$dir" >> "$LOG" 2>&1 ||
+            printResult 1 "Unable to mount $dir."
+    done
     printResult 0
-#    printResult $? "Unable to chroot into $WORK_DIR/$ROOT."
 } #}}}
 
 function get_firmwares #{{{
@@ -621,6 +633,15 @@ function fix_network #{{{
         echo -e "modules=\"g_ether\"" >> "$WORK_DIR/$ROOT/etc/conf.d/modules" 2>> "$LOG"
         printResult $? "Unable to add g_ether to modules list to load"
     fi
+    if [[ -n "$WPA_SUPP_FILE" ]]; then
+        echo -ne "\t- Copy wpa_supplicant.conf: "
+        [[ -d "$WORK_DIR/$ROOT/etc/wpa_supplicant" ]] ||
+            mkdir "$WORK_DIR/$ROOT/etc/wpa_supplicant" >> "$LOG" 2>&1 ||
+                printResult 1 "Unable to create /etc/wpa_supplicant directory."
+        LCONTENT="$WORK_DIR/$ROOT/etc/wpa_supplicant/wpa_supplicant.conf"
+        cp "$WPA_SUPP_FILE" "$LCONTENT" >> "$LOG" 2>&1
+        printResult $? "The copy failed."
+    fi
     if [[ "$SSH" = true ]]; then
         echo -ne "\t- Enabling ssh server: "
         (
@@ -806,15 +827,21 @@ function clean #{{{
         echo -ne "\t- Unmounting $CARD: "
         for dir in $(mount | grep "$WORK_DIR/$ROOT" | cut -f 3 -d " " | sort -r); do 
             umount "$dir" >> "$LOG" 2>&1 ||
-            printResult 1 "Unmounting $dir failed !" 0
+                printResult 1 "Unmounting $dir failed !" 0
         done
-        printResult 0
+        printResult 0 "" 0
         if [[ "$USE_IMG" = true && ! "$CARD" = "loopback" ]]; then
             echo -ne "\t- Destroying the virtual device $CARD: "
             losetup -d "$CARD" >> "$LOG" 2>&1
             printResult $? "Destroying $CARD failed !" 0
         fi
     else
+        echo -ne "\t- Unmounting $CARD: "
+        for dir in $(mount | grep "$WORK_DIR/$ROOT" | cut -f 3 -d " " | sort -r); do 
+            umount "$dir" >> "$LOG" 2>&1 ||
+                printResult 1 "Unmounting $dir failed !" 0
+        done
+        printResult 0 "" 0
         echo -ne "\t- Cleaning tarball files: "
         rm -Rf "${WORK_DIR:?}/${ROOT:?}/" >> "$LOG" 2>&1
         printResult $? "Unable to delete the files." 0
@@ -926,7 +953,7 @@ function get_password #{{{
 KRN_VERSION=$(git ls-remote "$KERNEL" | grep -v "pull\|patch" | grep head | 
             cut -d '/' -f 3 | grep "^rpi-[0-9].*y$" | sort -rV | head -n 1)
 
-while getopts "hb:m:B:d:k:c:H:t:f:C:M:F:-:" OPTION; do #{{{
+while getopts "hb:m:B:d:k:c:H:t:f:C:M:F:w:-:" OPTION; do #{{{
     case $OPTION in
         h ) show_help && exit 0 ;;
         b ) RPI_VERSION="$OPTARG"
@@ -963,6 +990,11 @@ while getopts "hb:m:B:d:k:c:H:t:f:C:M:F:-:" OPTION; do #{{{
             fi
             USE_MY_FSTAB=true
             FSTAB_FILE=$(readlink -f "$OPTARG") ;;
+        w ) if ! [[ -f "$OPTARG" ]]; then
+                echo "$OPTARG is not a file."
+                exit 1
+            fi
+            WPA_SUPP_FILE=$(readlink -f "$OPTARG") ;;
         - ) case $OPTARG in
                 add-kernel-src ) MOVE_KRN_SRC=true ;;
                 add-portage ) ADD_PORTAGE=true ;;
