Building a tarball to expand on a pre-formated sdcard

diff --git a/GenBerry b/GenBerry
--- a/GenBerry
+++ b/GenBerry
@@ -20,7 +20,9 @@ TUNE=false
 MOVE_KRN_SRC=false
 ADD_PORTAGE=false
 MY_CFG_TXT=false
+USE_MY_FSTAB=false
 USE_IMG=false
+USE_TARB=false
 NO_ETH=false
 NO_WLAN=false
 USE_SERIAL=false
@@ -59,11 +61,18 @@ function fix_actions #{{{
     IFS="$OLD_IFS"
 } #}}}
 
+# printResult
+# take 3 arguments
+# first (mandatory): the state (bool), 
+# second (optionnal): error message (string),
+# third (optional): stop clean propagation
+#
 function printResult #{{{
 {
     if [[ -z "$2" ]]; then local MESSAGE=""; else local MESSAGE="$2"; fi
     if [[ "$1" -ne 0 ]]; then
         echo -e "\e[1;31m[FAIL]\e[0m\n\t$MESSAGE"
+        [[ -z "$3" ]] && clean
         exit 1
     else
         echo -e "\e[1;32m[OK]\e[0m\e[37m"
@@ -79,7 +88,12 @@ function announce #{{{
     echo -e "* Device used: \e[1;31m$CARD\e[0m"
     echo -e "* Default root password: \e[1;33m$ROOT_PW\e[0m"
     echo -e "* Kernel version: \e[1;33m$KRN_VERSION\e[0m"
+    [[ "$USE_IMG" = true ]] && 
+        echo -e "* Location of the image: \e[1;33m$WORK_DIR/$FILE_PREFIX$RPI_VERSION-$MODE.img\e[0m"
+    [[ "$USE_TARB" = true ]] && 
+        echo -e "* Location of the tarball: \e[1;33m$WORK_DIR/$FILE_PREFIX$RPI_VERSION-$MODE.tar.xz\e[0m"
     [[ -n $MY_CFG ]] && echo "* Kernel configuration file used: \e[1;33m$MY_CFG\e[0m"
+    [[ -n $USE_MY_FSTAB ]] && echo "* fstab file used: \e[1;33m$FSTAB_FILE\e[0m"
     [[ "$MY_CFG_TXT" = true ]] && echo "* We use your own config.txt"
     echo -e "* RaspberryPi version: \e[1;33m$RPI_VERSION\e[0m"
     echo -e "* Architecture: \e[1;33m$MYARCH\e[0m"
@@ -122,13 +136,14 @@ function test_requirements #{{{
     SIZE_AVAIL=$(df -T "$WORK_DIR" | tail -n 1 | sed -E 's/( +)/ /g' | cut -d ' ' -f 5)
     [[ $(du "$WORK_DIR" | tail -n 1 | cut -f 1) -gt $THRESHOLD ]] && SIZE_NEED=0
     [[ "$USE_IMG" = true ]] && SIZE_NEED=$((SIZE_NEED + IMG_SIZE))
+    [[ "$USE_TARB" = true ]] && SIZE_NEED=$((SIZE_NEED + TARB_SIZE))
     printResult "$([[ $SIZE_NEED -lt $SIZE_AVAIL ]]; echo $?)" \
                                                 "You don't have enough space."
     echo -en "\t- Gentoo public key: "
     [[ $(gpg --list-key "$GLRE_KEY" >> "$LOG" 2>&1) ]] || 
         gpg --keyserver "$KEY_SERVER" --recv-keys "$GLRE_KEY" >> "$LOG" 2>&1
     printResult $? "You need to install the key: $GLRE_KEY."
-    if [[ "$USE_IMG" = false ]]; then
+    if [[ "$USE_IMG" = false ]] && [[ "$USE_TARB" = false ]]; then
         echo -en "\t- Media inserted: "
         test -b "$CARD"
         printResult $? "You will need an sdcard inserted."
@@ -150,7 +165,7 @@ function prepare_card #{{{
     echo "* Preparing card:"
     if [[ "$USE_IMG" = true ]]; then
         echo -ne "\t- Creating the virtual disk: "
-        FILE="$WORK_DIR/${IMG_PREFIX}_${RPI_VERSION}.img"
+        FILE="$WORK_DIR/$FILE_PREFIX$RPI_VERSION-$MODE.img"
         dd if=/dev/zero of="$FILE" bs="$BLOC_SIZE" count="$NBR_BLOCS" >> "$LOG" 2>&1 ||
             printResult 1 "File creation failed !"
         losetup -fP "$FILE" >> "$LOG" 2>&1
@@ -191,11 +206,6 @@ function mount_root #{{{
     else
         PART="$CARD"
     fi
-    [[ -d "$WORK_DIR/$ROOT" ]] ||
-        {
-            mkdir "$WORK_DIR/$ROOT" >> "$LOG" 2>&1 ||
-                printResult 1 "Mounting the root partition failed !"
-        }
     mount "${PART}3" "$WORK_DIR/$ROOT" >> "$LOG" 2>&1
     printResult $? "Mounting the root partition failed !"
     echo -ne "\t- boot: "
@@ -618,6 +628,14 @@ function fix_time #{{{
     )
 } #}}}
 
+function create_tarball #{{{
+{
+    echo -ne "* Creating the tarball: "
+    tar -cJf "$WORK_DIR/$FILE_PREFIX$RPI_VERSION-$MODE.tar.xz" \
+                                -C "$WORK_DIR/$ROOT" ./ >> "$LOG" 2>&1
+    printResult $? "Failed to create the file."
+} #}}}
+
 function fstab_builder #{{{
 {
     for INDEX in $1; do
@@ -646,11 +664,20 @@ function firstRun_builder #{{{
 function tune #{{{
 {
     echo "* Tuning system: "
-    # fstab
-    FSTAB=$(sfdisk -l "$CARD" -o Device | grep "^$CARD")
-    echo -ne "\t- Tuning fstab: "
-    fstab_builder "$FSTAB" > "$WORK_DIR/$ROOT/etc/fstab"
-    printResult $? "fstab tuning failed !"
+    if [[ "$USE_TARB" = false ]]; then
+        FSTAB=$(sfdisk -l "$CARD" -o Device | grep "^$CARD")
+        echo -ne "\t- Tuning fstab: "
+        fstab_builder "$FSTAB" > "$WORK_DIR/$ROOT/etc/fstab"
+        printResult $? "fstab tuning failed !"
+    elif [[ "$USE_MY_FSTAB" = true ]]; then
+            echo -ne "\t- Copying fstab: "
+            cp "$FSTAB_FILE" "$WORK_DIR/$ROOT/etc/fstab" >> "$LOG" 2>&1
+            printResult $? "Copy failed !"
+    fi
+    echo -ne "\t- Tuning cmdline.txt: "
+    sed -E "s/\s+/ /g" < "$WORK_DIR/$ROOT/etc/fstab" | cut -d ' ' -f 1,2,3 | grep "/ " | 
+        sed -E 's/([^ ]*) ([^ ]*) ([^ ]*)/root=\1 rootfstype=\3 rootwait/' > "$WORK_DIR/$ROOT/boot/cmdline.txt"
+    printResult $? "cmdline.txt file installing failed !"
     echo -ne "\t- Fixing root password: "
     sed -i "s|root:\*:|root:$ROOT_PW_HASH:|" "$WORK_DIR/$ROOT/etc/shadow"
     printResult $? "Fixing root password failed !"
@@ -661,22 +688,17 @@ function tune #{{{
 
     echo -ne "\t- Tuning config.txt: "
     if [[ "$MY_CFG_TXT" = true ]]; then
-        cp "$CONFIG_FILE" "$WORK_DIR/$ROOT/boot/config.txt" 2>> "$LOG"
+        cp "$CONFIG_TXT_CONTENT" "$WORK_DIR/$ROOT/boot/config.txt" 2>> "$LOG"
         printResult $? "Config file installing failed !"
     else
-        [[ $MODE -eq 64 ]] && CONFIG_FILE="${CONFIG_FILE}\narm_64bit=1"
+        [[ $MODE -eq 64 ]] && CONFIG_TXT_CONTENT="${CONFIG_TXT_CONTENT}\narm_64bit=1"
         if [[ $RPI_VERSION = "0W" ]] || [[ $RPI_VERSION = "3" ]] || 
             [[ $RPI_VERSION = "3P" ]] || [[ $RPI_VERSION = "4" ]]; then
-                CONFIG_FILE="$CONFIG_FILE\ndtparam=krnbt=on"
+                CONFIG_TXT_CONTENT="$CONFIG_TXT_CONTENT\ndtparam=krnbt=on"
         fi
-        echo -e "$CONFIG_FILE" > "$WORK_DIR/$ROOT/boot/config.txt" 2>> "$LOG"
+        echo -e "$CONFIG_TXT_CONTENT" > "$WORK_DIR/$ROOT/boot/config.txt" 2>> "$LOG"
         printResult $? "Config file installing failed !"
     fi
-    
-    echo -ne "\t- Tuning cmdline.txt: "
-    sed -E "s/\s+/ /g" < "$WORK_DIR/$ROOT/etc/fstab" | cut -d ' ' -f 1,2,3 | grep "/ " | 
-        sed -E 's/([^ ]*) ([^ ]*) ([^ ]*)/root=\1 rootfstype=\3 rootwait/' > "$WORK_DIR/$ROOT/boot/cmdline.txt"
-    printResult $? "cmdline.txt file installing failed !"
 
     if [[ "$USE_SERIAL" = true ]]; then
         echo -ne "\t- Configure serial comm: "
@@ -714,20 +736,24 @@ function tune #{{{
 function clean #{{{
 {
     echo "* Cleaning system: "
-    echo -ne "\t- Syncing filesystem: "
-    sync >> "$LOG" 2>&1
-    printResult $? "Syncing failed !"
-    echo -ne "\t- Unmounting $CARD: "
-    [[ 0 -eq $(mount | grep -c "$CARD") ]] || 
-                umount "$WORK_DIR/$ROOT"/{boot,} >> "$LOG" 2>&1
-    printResult $? "Unmounting $CARD failed !"
-    [[ "$USE_IMG" = true ]] && 
-        {
+    if [[ "$USE_TARB" = false ]]; then
+        echo -ne "\t- Syncing filesystem: "
+        sync >> "$LOG" 2>&1
+        printResult $? "Syncing failed !" 0
+        echo -ne "\t- Unmounting $CARD: "
+        [[ 0 -eq $(mount | grep -c "$CARD") ]] || 
+                    umount "$WORK_DIR/$ROOT"/{boot,} >> "$LOG" 2>&1
+        printResult $? "Unmounting $CARD failed !" 0
+        if [[ "$USE_IMG" = true ]] && ! [[ "$CARD" = "loopback" ]]; then
             echo -ne "\t- Destroying the virtual device $CARD: "
-            losetup -d "$CARD"
-            printResult $? "Destroying $CARD failed !"
-        }
-    #rm -rf "$WORK_DIR"
+            losetup -d "$CARD" >> "$LOG" 2>&1
+            printResult $? "Destroying $CARD failed !" 0
+        fi
+    else
+        echo -ne "\t- Cleaning tarball files: "
+        rm -Rf "${WORK_DIR:?}/${ROOT:?}/" >> "$LOG" 2>&1
+        printResult $? "Unable to delete the files." 0
+    fi
 } #}}}
 
 function show_help #{{{
@@ -769,17 +795,21 @@ Option's list:
 \t-M <size>\tMode: 32 or 64 bits
 \t\t\tThis apply only on rPi 3, 3P and 4
 \t\t\tActual value: $MODE\n
+\t-F <file>\tUse your own fstab file.
+\t\t\tOnly for use in conjonction with the -T option.\n
 \t-s\t\tCopy the kernel sources on the card,
-\t\t\tBeware that this will run make distclean on the actual sources
+\t\t\tBeware that this will run make distclean on the actual sources.
 \t\t\tActual value is \"$MOVE_KRN_SRC\"\n
 \t-p\t\tCopy the portage tree,
 \t\t\tActual value is \"$ADD_PORTAGE\"\n
-\t-i\t\tBuild an image instead of writing directly on the media\n
-\t-u\t\tEnable serial communications
-\t\t\tMight disable bluetooth on some card\n
-\t-U\t\tEnable usb tethering
-\t\t\tNeed some tweak on your computer\n
-\t-S\t\tEnable sshd service with root login allowed\n
+\t-i\t\tBuild an image instead of writing directly on the media.\n
+\t-T\t\tBuild a tarball instead of writing directly on the media.
+\t\t\tIf you want a valid fstab, you have to privide it with the -F option.\n
+\t-u\t\tEnable serial communications.
+\t\t\tMight disable bluetooth on some card.\n
+\t-U\t\tEnable usb tethering.
+\t\t\tNeed some tweak on your computer.\n
+\t-S\t\tEnable sshd service with root login allowed.\n
 After the first boot, follow those steps:\n
 \t* emerge --sync
 \t* perl-cleaner --all
@@ -803,13 +833,20 @@ function build_workplace #{{{
             }
         WORK_DIR=$(cd "$WP_TMP" && pwd)
     fi
+    if ! [[ -d "$WORK_DIR/$ROOT" ]]; then
+        mkdir "$WORK_DIR/$ROOT" >> /dev/null 2>&1
+        if [[ $? = 1 ]]; then
+            echo  "Creating the root partition failed !"
+            exit 1
+        fi
+    fi
 } #}}}
 
 # Retrieve the last kernel version
 KRN_VERSION=$(git ls-remote "$KERNEL" | grep -v "pull\|patch" | grep head | 
             cut -d '/' -f 3 | grep "^rpi-[0-9].*y$" | sort -rV | head -n 1)
 
-while getopts "hb:m:B:d:k:c:H:t:f:a:C:M:spiuUS" OPTION; do #{{{
+while getopts "hb:m:B:d:k:c:H:t:f:a:C:M:F:spiuUST" OPTION; do #{{{
     case $OPTION in
         h ) show_help && exit 0 ;;
         b ) RPI_VERSION="$OPTARG"
@@ -821,29 +858,32 @@ while getopts "hb:m:B:d:k:c:H:t:f:a:C:M:spiuUS" OPTION; do #{{{
         B ) KRN_VERSION="$OPTARG" ;;
         d ) CARD="$OPTARG" ;;
         k ) KEYMAPS="$OPTARG" ;;
-        c ) [[ -f "$OPTARG" ]] ||
-                {
-                    echo "$OPTARG is not a file."
-                    exit 1
-                }
+        c ) if ! [[ -f "$OPTARG" ]]; then
+                echo "$OPTARG is not a file."
+                exit 1
+            fi
             MY_CFG=$(readlink -f "$OPTARG") ;;
         H ) HN="$OPTARG" ;;
         t ) TZ="$OPTARG" ;;
         f ) ROOT_FS="$OPTARG" ;;
         a ) fix_actions "$OPTARG" ;;
-        C ) [[ -f "$OPTARG" ]] ||
-                {
-                    echo "$OPTARG is not a file."
-                    exit 1
-                }
+        C ) if ! [[ -f "$OPTARG" ]]; then
+                echo "$OPTARG is not a file."
+                exit 1
+            fi
             MY_CFG_TXT=true
-            CONFIG_FILE="$OPTARG" ;;
-        M ) [[ $OPTARG -ne 32 && $OPTARG -ne 64 ]] &&
-                {
-                    echo "-M allowed values are: 32 and 64."
-                    exit 1
-                }
+            CONFIG_TXT_CONTENT="$OPTARG" ;;
+        M ) if [[ $OPTARG -ne 32 && $OPTARG -ne 64 ]]; then
+                echo "-M allowed values are: 32 and 64."
+                exit 1
+            fi
             MODE=$OPTARG ;;
+        F ) if ! [[ -f "$OPTARG" ]]; then
+                echo "$OPTARG is not a file."
+                exit 1
+            fi
+            USE_MY_FSTAB=true
+            FSTAB_FILE="$OPTARG" ;;
         s ) MOVE_KRN_SRC=true ;;
         p ) ADD_PORTAGE=true ;;
         i ) USE_IMG=true
@@ -851,6 +891,8 @@ while getopts "hb:m:B:d:k:c:H:t:f:a:C:M:spiuUS" OPTION; do #{{{
         u ) USE_SERIAL=true ;;
         U ) USE_TETHER=true ;;
         S ) SSH=true ;;
+        T ) USE_TARB=true
+            CARD=tarball ;;
         * ) show_help && exit 1 ;;
     esac
 done #}}}
@@ -887,10 +929,13 @@ touch "$LOG" > /dev/null
 test_requirements
 $GET_CONTENT && get_contents
 $BUILDK && build_kernel
-$PREPARE && prepare_card
-( $POPULATE || $TUNE ) && mount_root
+if [[ "$USE_TARB" = false ]]; then
+    $PREPARE && prepare_card
+    ( $POPULATE || $TUNE ) && mount_root
+fi
 $POPULATE && populate
 $TUNE && tune
 [[ "$NO_ETH" = false ]] && firstRun_builder
+[[ "$USE_TARB" = true ]] && create_tarball
 clean
 exit 0
