Adding config options to scripts via interface

diff --git a/imagebuilder b/imagebuilder
--- a/imagebuilder
+++ b/imagebuilder
@@ -1,15 +1,13 @@
 #!/bin/bash
 # vim: foldmarker={{{,}}}
 #
-# imagebuilder.sh
+# imagebuilder
 # Author: Alexandre Keledjian <dervishe@yahoo.fr>
 # Version: 1.0
 # License: GPLv3
 # 
 #
 # This script build an sdcard image
-#	Parameters list:
-#		rPi type 1(A, A+, B, B+, zero) or 2
 #
 
 #{{{ Parameters
@@ -18,31 +16,106 @@ FILE=genBerry.tar.xz
 SIG=${FILE}.gpgsig
 HASH=${FILE}.md5sum
 DEVICE=/dev/mmcblk0
-MOUNT_POINT=./mnt
-WDIR=./repository
-RASP_TYPE="$1"
-echo $RASP_TYPE
+MOUNT_POINT=mnt
+WDIR=repository
+RASP_TYPE=1
+VERBOSE=0
+CHECK_SIGN=1
+KEEP_FILES=0
+NO_DISK=0
+NO_NET=0
+NO_FBTFT=0
+FLAG_FBTFT=""
+FLAG_KEEP_FILES=""
+FLAG_CHECK_SIGN=""
 # Check for a correct raspberry type
-if ! [[ $RASP_TYPE -eq 1 ]] && ! [[ $RASP_TYPE -eq 2 ]]; then
-	echo "Bad RaspBerry type (1|2): $RASP_TYPE"
-	exit 1
-fi
 # Here we assume that each sector's size is 512 bytes
 DISK_SIZE=$(($(sfdisk -s $DEVICE) * 2))
 LAYOUT="2048,65536,c\n67584,,83"
 [[ $DISK_SIZE -lt 8388608 ]] && TAG_EXT4="-T small" || TAG_EXT4=""
 #}}}
-. ./helpers.sh
+#{{{ Library
+function show_help() #{{{
+{
+	echo "
+usage: $0 <options>
 
+Option's list:
+
+	-b <type>			Type of the board: 
+					1/ for raspberryPi (1 A A+ B B+ and zero) and 
+					2/ for raspberryPi (2 A and B)
+					Default type is 1
+	-d <dev>			Set the device used to store the system (/dev/mmcblk0)
+	-m <dir>			Set the mount point for the disk (./mnt)
+	-h : --help			Display this help message
+	-c : --dont-check		Don't check the several files signature
+	-n : --no-disk			You have to prepare the disk yourself (partitionning, formating and mounting) and you MUST use this option
+					in conjonction with -m in order to indicate the mount point. In this case, it is necessary to adjust the /etc/fstab
+					located in the media.
+	-k : --keep-files		Keep all the files retrieved (archives, hash, signature, etc)
+	-w : --without-fbtft		Don't include the Notro fbtft drivers
+	-i : --no-auto-net			Disable network interface startup at boot time (for the raspberry without network interface like zero)
+"
+} #}}}
+#}}}
+. ./helpers
+
+#{{{ Parameters analyzis
+while getopts "hcnikwb:d:m:-:" option; do
+	case $option in
+		h ) show_help && exit 0 ;;
+		c ) CHECK_SIGN=0; FLAG_CHECK_SIGN="--dont-check" ;;
+		n ) NO_DISK=1 ;;
+		i ) NO_NET=1 ;;
+		k ) KEEP_FILES=1; FLAG_KEEP_FILES="--keep-files";;
+		w ) NO_FBTFT=1; FLAG_FBTFT="--without-fbtft";;
+		b ) RASP_TYPE=$OPTARG
+			if ! [[ $RASP_TYPE -eq 1 ]] && ! [[ $RASP_TYPE -eq 2 ]]; then
+				echo "Bad RaspBerry type: $RASP_TYPE"
+				show_help
+				exit 1
+			fi;;
+		m ) MOUNT_POINT=$OPTARG
+			if ! [[ -d $MOUNT_POINT ]]; then
+				echo "$MOUNT_POINT doesn't exist."
+				show_help
+				exit 1
+			fi;;
+		d ) DEVICE=$OPTARG
+			if ! [[ -b $DEVICE ]]; then
+				echo "$DEVICE doesn't exist."
+				show_help
+				exit 1
+			fi;;
+		- ) case $OPTARG in
+				help ) show_help && exit 0 ;;
+				dont-check ) CHECK_SIGN=0; FLAG_CHECK_SIGN="--dont-check" ;;
+				keep-files ) KEEP_FILES=1; FLAG_KEEP_FILES="--keep-files";;
+				no-disk ) NO_DISK=1 ;;
+				no-auto-net ) NO_NET=1 ;;
+				without-fbtft ) NO_FBTFT=1; FLAG_FBTFT="--without-fbtft";;
+				* ) echo "Unknown option: ${OPTARG}"
+					show_help
+					exit -1 ;;
+			esac ;;
+		? ) echo "Unknown option: ${OPTARG}"
+			show_help
+			exit -1 ;;
+	esac
+done
+#}}}
 clear
-echo -e "$HSTAR Checking requirements (1/13): " #{{{
+echo -e "$HSTAR Checking requirements (1/14): " #{{{
 echo -en "\t$HSTAR Is ${DEVICE} exists ? "
 ls $DEVICE >> $LOG 2>&1
 BUFFER=$?
 printResult $BUFFER
 [[ $BUFFER -ne 0 ]] && exit 1
-echo -en "\t$HSTAR Is gpg installed ? "
-checkGPG
+if [[ $CHECK_SIGN -ne 0 ]]; then
+	echo -en "\t$HSTAR Is gpg installed ? "
+	checkGPG
+fi
 echo -en "\t$HSTAR Is partprobe installed ? "
 which partprobe >> $LOG 2>&1
 BUFFER=$?
@@ -58,47 +131,50 @@ read rep
 [[ $rep =~ [Yy](es)? ]] || exit 1
 echo -e "\nThe log file will be stored here: ${LOG}\n"
 
-echo -en "$HSTAR Building working dir (2/13): " #{{{
+echo -en "$HSTAR Building working dir (2/14): " #{{{
 ([[ -d $WDIR ]] || mkdir "$WDIR") && cd "$WDIR" >> $LOG 2>&1
 printResult $?
 #}}}
 
-echo -en "$HSTAR Retrieving the fingerprint (3/13): " #{{{
+echo -en "$HSTAR Retrieving the fingerprint (3/14): " #{{{
 [[ -f $HASH ]] && rm $HASH
 getFile $LOCATION/$HASH
 #}}}
 
-echo -en "$HSTAR Retrieving stage 4 (4/13): " #{{{
+echo -en "$HSTAR Retrieving stage 4 (4/14): " #{{{
 retrieveFile $FILE $HASH $LOCATION
 #}}}
 
-echo -en "$HSTAR Checking the new file's fingerprint (5/13): " #{{{
+echo -en "$HSTAR Checking the new file's fingerprint (5/14): " #{{{
 checkFingerprint $HASH
 #}}}
 
-echo -en "$HSTAR Retrieving the file's signature (6/13): " #{{{
-getFile $LOCATION/$SIG
-#}}}
+if [[ $CHECK_SIGN -ne 0 ]]; then
+	echo -en "$HSTAR Retrieving the file's signature (6/14): " #{{{
+	getFile $LOCATION/$SIG
+	#}}}
 
-echo -en "$HSTAR Checking file's signature (7/13): " #{{{
-checkSignature $SIG $FILE
-if [[ $? -ne 0 ]]; then
-	echo -e "\tSignature's problem: the file don't seems to be legit..."
-	echo -e "\tPerhap's you don't have imported my public key:"
-	echo -e "\thttps://keybase.io/dervishe/key.asc"
-	exit 1;
+	echo -en "$HSTAR Checking file's signature (7/14): " #{{{
+	checkSignature $SIG $FILE
+	if [[ $? -ne 0 ]]; then
+		echo -e "\tSignature's problem: the file don't seems to be legit..."
+		echo -e "\tPerhap's you don't have imported my public key:"
+		echo -e "\thttps://keybase.io/dervishe/key.asc"
+		exit 1;
+	fi
+	#}}}
 fi
-#}}}
 
-echo -en "$HSTAR Partitionning the sdcard (8/13): " #{{{
-echo -e $LAYOUT | sfdisk $DEVICE >> $LOG 2>&1
-partprobe $DEVICE >> $LOG 2>&1
-BUFFER=$?
-printResult $BUFFER
-[[ $BUFFER -eq 0 ]] || exit 1
-#}}}
+if [[ $NO_DISK -eq 0 ]]; then
+	echo -en "$HSTAR Partitionning the sdcard (8/14): " #{{{
+	echo -e $LAYOUT | sfdisk $DEVICE >> $LOG 2>&1
+	partprobe $DEVICE >> $LOG 2>&1
+	BUFFER=$?
+	printResult $BUFFER
+	[[ $BUFFER -eq 0 ]] || exit 1
+	#}}}
 
-echo -e "$HSTAR Formating the sdcard (9/13): " #{{{
+echo -e "$HSTAR Formating the sdcard (9/14): " #{{{
 BOOT=$(sfdisk -l $DEVICE | grep "^/dev" | cut -d ' ' -f 1 | grep 1)
 ROOT=$(sfdisk -l $DEVICE | grep "^/dev" | cut -d ' ' -f 1 | grep 2)
 echo -en "\t$HSTAR $BOOT in FAT16: "
@@ -114,7 +190,7 @@ printResult $BUFFER
 [[ $BUFFER -eq 0 ]] || exit 1
 #}}}
 
-echo -e "$HSTAR Mounting partitions (10/13): " #{{{
+echo -e "$HSTAR Mounting partitions (10/14): " #{{{
 echo -en "\t$HSTAR root: "
 [[ -d $MOUNT_POINT ]] || mkdir $MOUNT_POINT >> $LOG 2>&1
 mount $ROOT $MOUNT_POINT
@@ -133,8 +209,9 @@ BUFFER=$?
 printResult $BUFFER
 [[ $BUFFER -eq 0 ]] || exit 1
 #}}}
+fi
 
-echo -en "$HSTAR Expanding the image on sdcard (11/13): " #{{{
+echo -en "$HSTAR Expanding the image on sdcard (11/14): " #{{{
 tar -xJpf $FILE -C $MOUNT_POINT >> $LOG 2>&1
 BUFFER=$?
 printResult $BUFFER
@@ -145,22 +222,24 @@ if [[ $BUFFER -ne 0 ]]; then
 	umount ${MOUNT_POINT}/{boot,} >> $LOG 2>&1
 	exit 1;
 fi
+# Cleaning the net.eth0 from runlevel default
+[[ $NO_NET -eq 1 ]] && rm ${MOUNT_POINT}/etc/runlevels/default/net.eth0 >> $LOG 2>&1
 #}}}
 
-echo -e "$HSTAR Installing new kernel (12/13): " #{{{
+echo -e "$HSTAR Installing new kernel (12/14): " #{{{
 cd .. >> $LOG 2>&1
-./kernelbuilder.sh ../../${WDIR}/$MOUNT_POINT $RASP_TYPE $LOCATION
+./kernelbuilder -m $(pwd)/${WDIR}/$MOUNT_POINT -b $RASP_TYPE $FLAG_FBTFT $FLAG_KEEP_FILES
 cd - >> $LOG 2>&1
 #}}}
 
-echo -e "$HSTAR Creating portage tree on squashfs (13/13): " #{{{
+echo -e "$HSTAR Creating portage tree on squashfs (13/14): " #{{{
 cd .. > /dev/null 2>&1
-${WDIR}/${MOUNT_POINT}/root/portage/portage2squa.sh
+./portage2squash $FLAG_KEEP_FILES $FLAG_CHECK_SIGN
 mv ./portage.squashfs ${WDIR}/${MOUNT_POINT}/root/portage/ > /dev/null 2>&1
 cd - > /dev/null 2>&1
 #}}}
 
-echo -e "$HSTAR Cleaning all the stuffs (14/13): " #{{{
+echo -e "$HSTAR Cleaning all the stuffs (14/14): " #{{{
 echo -en "\t$HSTAR Syncing sdcard: "
 sync && printResult 0
 echo -en "\t$HSTAR Unmounting directory: "
@@ -169,13 +248,15 @@ BUFFER=$?
 printResult $BUFFER
 [[ $BUFFER -ne 0 ]] && exit 1
 cd .. >> $LOG 2>&1
-echo -en "\t$HSTAR Deleting stuffs: "
-rm -Rf $WDIR >> $LOG 2>&1
-BUFFER=$?
-printResult $BUFFER
-if [[ $BUFFER -ne 0 ]]; then
-	echo -e "\tUnable to clean and delete the temporary directory"
-	exit 1
+if [[ $KEEP_FILES -ne 1 ]]; then
+	echo -en "\t$HSTAR Deleting stuffs: "
+	rm -Rf $WDIR >> $LOG 2>&1
+	BUFFER=$?
+	printResult $BUFFER
+	if [[ $BUFFER -ne 0 ]]; then
+		echo -e "\tUnable to clean and delete the temporary directory"
+		exit 1
+	fi
 fi
 #}}}
 exit 0
diff --git a/kernelbuilder b/kernelbuilder
--- a/kernelbuilder
+++ b/kernelbuilder
@@ -1,36 +1,83 @@
 #!/bin/bash
 # vim: foldmarker={{{,}}}
 #
-# kernelbuilder.sh
+# kernelbuilder
 # Author: Alexandre Keledjian <dervishe@yahoo.fr>
 # Version: 1.0
 # License: GPLv3
 #
 #
 # This script build the kernel image for the raspberryPi
-#	Parameters list:
-#		modules install path
-#		rPi type:	1 for (A, A+, B, B+ and zero) or 2 for 2A and 2B
-#		server address
-
+#
 
 #{{{ Parameters
 KERNEL_SOURCES=git://github.com/raspberrypi/linux.git
 FBTFT_SOURCES=git://github.com/notro/fbtft.git
-ROOT_PATH="$1"
+ROOT_PATH=""
 TARGET=/usr/bin/armv6j-hardfloat-linux-gnueabi-
 WDIR=./repository_alt
-LOCATION="$3"
-RASP_TYPE="$2"
-# Check for a correct raspberry type
-if ! [[ $RASP_TYPE  -eq 1 ]] && ! [[ $RASP_TYPE -eq 2 ]]; then
-	echo "Bad RaspBerry type (1|2): $RASP_TYPE"
+RASP_TYPE=1
+KEEP_FILES=0
+NO_FBTFT=0
+#}}}
+#{{{ Library
+function show_help() #{{{
+{
+	echo "
+usage: $0 -b board_type -m mount_point <options>
+
+Option's list:
+
+	-b <type>			Type of the board: [Mandatory]
+					1/ for raspberryPi (1 A A+ B B+ and zero) and 
+					2/ for raspberryPi (2 A and B)
+					Default type is 1
+	-m <dir>			Set the mount point for the disk (./mnt) [Mandatory]
+	-h : --help			Display this help message
+	-k : --keep-files		Keep all the files retrieved (archives, hash, signature, etc)
+	-w : --without-fbtft		Don't include the Notro fbtft drivers
+"
+} #}}}
+#}}}
+. ./helpers
+
+#{{{ Parameters analyzis
+while getopts "hkwb:m:-:" option; do
+	case $option in
+		h ) show_help && exit 0 ;;
+		k ) KEEP_FILES=1;;
+		w ) NO_FBTFT=1;;
+		b ) RASP_TYPE=$OPTARG
+			if ! [[ $RASP_TYPE -eq 1 ]] && ! [[ $RASP_TYPE -eq 2 ]]; then
+				echo "Bad RaspBerry type: $RASP_TYPE"
+				show_help
+				exit 1
+			fi;;
+		m ) ROOT_PATH=$OPTARG
+			if ! [[ -d $ROOT_PATH ]]; then
+				echo "$ROOT_PATH doesn't exist."
+				exit 1
+			fi;;
+		- ) case $OPTARG in
+				help ) show_help && exit 0 ;;
+				keep-files ) KEEP_FILES=1;;
+				without-fbtft ) NO_FBTFT=1;;
+				* ) echo "Unknown option: ${OPTARG}"
+					show_help
+					exit -1 ;;
+			esac ;;
+		? ) echo "Unknown option: ${OPTARG}"
+			show_help
+			exit -1 ;;
+	esac
+done
+#}}}
+if [[ $ROOT_PATH = "" ]]; then
+	echo "You didn't provide the mount point for the disk"
+	show_help
 	exit 1
 fi
-#}}}
-. ./helpers.sh
-
-echo -e "\t$HSTAR Checking requirements: " #{{{
+echo -e "\t$HSTAR Checking requirements (1/9): " #{{{
 echo -en "\t\t$HSTAR Are you root ? "
 checkRoot
 echo -en "\t\t$HSTAR Are you connected ? "
@@ -41,26 +88,28 @@ echo -en "\t\t$HSTAR Kernel building tools installed ? "
 checkKBT
 #}}}
 
-echo -en "\t$HSTAR Building working dir: " #{{{
+echo -en "\t$HSTAR Building working dir (2/9): " #{{{
 ([[ -d $WDIR ]] || mkdir "$WDIR") && cd "$WDIR" >> $LOG 2>&1
 printResult $?
 #}}}
 
-echo -en "\t$HSTAR Retrieving the kernel source: " #{{{
-git clone --depth 1 $KERNEL_SOURCES >> $LOG 2>&1
+echo -en "\t$HSTAR Retrieving the kernel source (3/9): " #{{{
+[[ -d ./linux ]] || git clone --depth 1 $KERNEL_SOURCES >> $LOG 2>&1
 printResult $?
 #}}}
 
-echo -en "\t$HSTAR Retrieving the notro fbtft source: " #{{{
-cd ./linux/drivers/video/fbdev >> $LOG 2>&1
-git clone $FBTFT_SOURCES >> $LOG 2>&1
-echo "source \"drivers/video/fbdev/fbtft/Kconfig\"" >> ./Kconfig
-echo "obj-y += fbtft/" >> ./Makefile
-cd - >> $LOG 2>&1
-printResult $?
-#}}}
+if [[ $NO_FBTFT -eq 0 ]]; then
+	echo -en "\t$HSTAR Retrieving the notro fbtft source (4/9): " #{{{
+	cd ./linux/drivers/video/fbdev >> $LOG 2>&1
+	git clone $FBTFT_SOURCES >> $LOG 2>&1
+	echo "source \"drivers/video/fbdev/fbtft/Kconfig\"" >> ./Kconfig
+	echo "obj-y += fbtft/" >> ./Makefile
+	cd - >> $LOG 2>&1
+	printResult $?
+	#}}}
+fi
 
-echo -e "\t$HSTAR Compiling the kernel (You can take a coffee now): " #{{{
+echo -e "\t$HSTAR Compiling the kernel (You can take a coffee now) (5/9): " #{{{
 cd ./linux >> $LOG 2>&1
 
 echo -en "\t\t$HSTAR Configure BCM chip: "
@@ -81,21 +130,21 @@ make ARCH=arm CROSS_COMPILE=$TARGET -j$(( $NB_CORE + 1 )) -l$NB_CORE >> $LOG 2>&
 printResult $?
 #}}}
 
-echo -en "\t$HSTAR Installing the modules: " #{{{
+echo -en "\t$HSTAR Installing the modules (6/9): " #{{{
 make ARCH=arm CROSS_COMPILE=$TARGET modules_install INSTALL_MOD_PATH=$ROOT_PATH >> $LOG 2>&1
 BUFFER=$?
 printResult $BUFFER
 [[ $BUFFER -eq 1 ]] && exit 1
 # Adjusting the symbolic link
 KERN_VERSION=$(cat .config | grep Linux | cut -d ' ' -f 3)
-cd ${ROOT_PATH}/lib/modules/${KERN_VERSION}*
-rm ./build ./source
-ln -s /usr/src/linux ./build
-ln -s /usr/src/linux ./source
-cd -
+cd ${ROOT_PATH}/lib/modules/${KERN_VERSION}* >> $LOG 2>&1
+rm ./build ./source >> $LOG 2>&1
+ln -s /usr/src/linux ./build >> $LOG 2>&1
+ln -s /usr/src/linux ./source >> $LOG 2>&1
+cd - >> $LOG 2>&1
 #}}}
 
-echo -en "\t$HSTAR Installing the kernel: " #{{{
+echo -en "\t$HSTAR Installing the kernel (7/9): " #{{{
 if [[ $RASP_TYPE -eq 1 ]]; then
 	imagetool-uncompressed.py arch/arm/boot/Image ${ROOT_PATH}/boot/kernel.img >> $LOG 2>&1
 elif [[ $RASP_TYPE -eq 2 ]]; then
@@ -107,20 +156,23 @@ cp arch/arm/boot/dts/overlays/README ${ROOT_PATH}/boot/overlays/ >> $LOG 2>&1
 printResult $?
 #}}}
 
-echo -en "\t$HSTAR Installing the kernel config file: " #{{{
+echo -en "\t$HSTAR Installing the kernel config file (8/9): " #{{{
 cp .config ${ROOT_PATH}/usr/src/linux/ >> $LOG 2>&1
 printResult $?
 #}}}
 
-echo -e "\t$HSTAR Cleaning all the stuffs: " #{{{
-echo -en "\t\t$HSTAR Deleting stuffs: "
+echo -e "\t$HSTAR Cleaning all the stuffs (9/9): " #{{{
 cd ../../
-rm -Rf $WDIR >> $LOG 2>&1
-BUFFER=$?
-printResult $BUFFER
-if [[ $BUFFER -ne 0 ]]; then
-	echo -e "\t\t\tUnable to clean and delete the temporary directory"
-	exit 1
+if [[ $KEEP_FILES -ne 1 ]]; then
+	echo -en "\t\t$HSTAR Deleting stuffs: "
+	rm -Rf $WDIR >> $LOG 2>&1
+	BUFFER=$?
+	printResult $BUFFER
+	if [[ $BUFFER -ne 0 ]]; then
+		echo -e "\t\t\tUnable to clean and delete the temporary directory"
+		exit 1
+	fi
 fi
 cd .. >> $LOG 2>&1
 #}}}
+exit 0
diff --git a/portage2squash b/portage2squash
--- a/portage2squash
+++ b/portage2squash
@@ -1,7 +1,7 @@
 #!/bin/bash
 # vim: foldmarker={{{,}}}
 #
-# portage2squa.sh
+# portage2squash
 # Author: Alexandre Keledjian <dervishe@yahoo.fr>
 # Version: 1.0
 # License: GPLv3
@@ -19,12 +19,51 @@ WDIR=./repository_alt
 TEST_DIR=./mnt
 SQUASH_FILE=portage.squashfs
 LOCAL_PORTAGE_DIR=portage
+CHECK_SIGN=1
+KEEP_FILES=0
 #}}}
-. ./helpers.sh
+#{{{ Library
+function show_help() #{{{
+{
+	echo "
+usage: $0 <options>
+
+Option's list:
+
+	-h : --help			Display this help message
+	-c : --dont-check		Don't check the several files signature
+	-k : --keep-files		Keep all the files retrieved (archives, hash, signature, etc)
+"
+} #}}}
+#}}}
+. ./helpers
+
+#{{{ Parameters analyzis
+while getopts "hckm:-:" option; do
+	case $option in
+		h ) show_help && exit 0 ;;
+		c ) CHECK_SIGN=0 ;;
+		k ) KEEP_FILES=1 ;;
+		- ) case $OPTARG in
+				help ) show_help && exit 0 ;;
+				dont-check ) CHECK_SIGN=0 ;;
+				keep-files ) KEEP_FILES=1 ;;
+				* ) echo "Unknown option: ${OPTARG}"
+					show_help
+					exit -1 ;;
+			esac ;;
+		? ) echo "Unknown option: ${OPTARG}"
+			show_help
+			exit -1 ;;
+	esac
+done
+#}}}
 
 echo -e "\t$HSTAR Checking requirements (1/11): " #{{{
-echo -en "\t\t$HSTAR Is gpg installed ? "
-checkGPG
+if [[ $CHECK_SIGN -ne 0 ]]; then
+	echo -en "\t\t$HSTAR Is gpg installed ? "
+	checkGPG
+fi
 echo -en "\t\t$HSTAR Are squashfs tools installed ? "
 which mksquashfs >> $LOG 2>&1
 BUFFER=$?
@@ -54,19 +93,21 @@ echo -en "\t$HSTAR Checking file's fingerprint (5/11): " #{{{
 checkFingerprint $HASH
 #}}}
 
-echo -en "\t$HSTAR Retrieving the file's signature (6/11): " #{{{
-getFile $LOCATION/$SIG
-#}}}
+if [[ $CHECK_SIGN -ne 0 ]]; then
+	echo -en "\t$HSTAR Retrieving the file's signature (6/11): " #{{{
+	getFile $LOCATION/$SIG
+	#}}}
 
-echo -en "\t$HSTAR Checking file's signature (7/11): " #{{{
-checkSignature $SIG $FILE
-if [[ $? -ne 0 ]]; then
-	echo -e "\t\tSignature's problem: the file don't seems to be legit..."
-	echo -e "\t\tPerhap's you don't have imported the Gentoo public key:"
-	echo -e "\t\thttps://www.gentoo.org/downloads/signatures/"
-	exit 1;
+	echo -en "\t$HSTAR Checking file's signature (7/11): " #{{{
+	checkSignature $SIG $FILE
+	if [[ $? -ne 0 ]]; then
+		echo -e "\t\tSignature's problem: the file don't seems to be legit..."
+		echo -e "\t\tPerhap's you don't have imported the Gentoo public key:"
+		echo -e "\t\thttps://www.gentoo.org/downloads/signatures/"
+		exit 1;
+	fi
+	#}}}
 fi
-#}}}
 
 echo -en "\t$HSTAR Expanding the portage tree (8/11): " #{{{
 tar -xJpf $FILE >> $LOG 2>&1
@@ -110,12 +151,16 @@ if [[ $BUFFER -ne 0 ]]; then
 	echo -e "\t\tUnable to move the squashfs file: '$SQUASH_FILE' from the temporary directory"
 	exit 1
 fi
-rm -Rf $WDIR >> $LOG 2>&1
-BUFFER=$?
-printResult $BUFFER
-if [[ $BUFFER -ne 0 ]]; then
-	echo -e "\t\tUnable to clean and delete the temporary directory"
-	exit 1
+if [[ $KEEP_FILES -ne 1 ]]; then
+	rm -Rf $WDIR >> $LOG 2>&1
+	BUFFER=$?
+	printResult $BUFFER
+	if [[ $BUFFER -ne 0 ]]; then
+		echo -e "\t\tUnable to clean and delete the temporary directory"
+		exit 1
+	fi
+else
+	printResult $BUFFER
 fi
 #}}}
 exit 0
